services:
    train:
        build: .
        volumes:
            - ./models:/usr/src/app/output
        runtime: nvidia
        resources:
            reservations:
                devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [ gpu ]
        command: >
            sh -c "sh train.sh && 
                   chown 1051:1051 -R runs"
