stages:
  select_and_export:
    cmd: python src/utils/preprocessing/export_data.py
    deps:
    - data
    - src/utils/preprocessing
    outs:
    - prepared_data
  train:
    cmd: docker-compose up
    deps:
    - prepared_data
    - models/params
    - src/utils/yolov5
    - src/train.sh
    params:
    - models/params/hyp.yaml
    outs:
    - models/weights
    - models/samples
    - models/metrics
