stages:

  prepare_opix:
    cmd: python src/data/prepare_opix.py
    deps:
    - opix_dataset/
    - src/data/prepare_opix.py
    outs:
    - prepared_opix

  pretrain:
    cmd: sh src/model/pretrain.sh
    deps:
    - prepared_opix
    - src/model
    outs:
    - models/pretrained
    params:
    - models/params/pretrain_hyp.yaml:
      - anchor_t
      - box
      - cls
      - cls_pw
      - copy_paste
      - degrees
      - fl_gamma
      - fliplr
      - flipud
      - hsv_h
      - hsv_s
      - hsv_v
      - iou_t
      - lr0
      - lrf
      - mixup
      - momentum
      - mosaic
      - obj
      - obj_pw
      - perspective
      - scale
      - shear
      - translate
      - warmup_bias_lr
      - warmup_epochs
      - warmup_momentum
      - weight_decay
  
  nms_pruning:
    cmd: python src/data/nms.py -i data/cargoxray -o stages/nms_pruning
    deps:
    - data/cargoxray
    - src/data/nms.py
    outs:
    - stages/nms_pruning

  prepare_cargoxray:
    cmd: python src/data/export_data.py --images_dir data/cargoxray/images --data_dir data/cargoxray --output_dir stages/prepare_cargoxray
    deps:
    - data/cargoxray
    - src/data/common
    - src/data/export_data.py
    outs:
    - stages/prepare_cargoxray

  train:
    cmd: sh src/model/train.sh
    deps:
    - stages/prepare_cargoxray
    - src/model
    outs:
    - stages/train
    params:
    - params/hyp.yaml:
      - anchor_t
      - box
      - cls
      - cls_pw
      - copy_paste
      - degrees
      - fl_gamma
      - fliplr
      - flipud
      - hsv_h
      - hsv_s
      - hsv_v
      - iou_t
      - lr0
      - lrf
      - mixup
      - momentum
      - mosaic
      - obj
      - obj_pw
      - perspective
      - scale
      - shear
      - translate
      - warmup_bias_lr
      - warmup_epochs
      - warmup_momentum
      - weight_decay

  evaluate:
    cmd: sh src/model/evaluate.sh
    deps:
    - stages/train
    - src/model
    - stages/prepare_cargoxray
    metrics:
    - stages/evaluate/results.json
g