stages:
  select_and_export:
    cmd: python src/data/export_data.py
    deps:
    - data
    - src/data
    outs:
    - prepared_data
  train:
    cmd: python src/model/yolov5/train.py \
          --weights yolov5s6.pt \
          --data prepared_data/dataset.yaml \
          --hyp models/params/hyp.yaml \
          --epochs 100 \
          --batch-size 32 \
          --imgsz 1024 \
          --device 0 \
          --project models \
          --name results \
          --cache
    deps:
    - prepared_data
    - models/params
    - src/model
    outs:
    - models/results
