stages:
  select_and_export:
    cmd: python src/utils/preprocessing/export_data.py
    deps:
    - data
    - src/utils/preprocessing
    outs:
    - prepared_data
  train:
    cmd: sh train_in_docker.sh
    deps:
    - prepared_data
    - src/utils/yolov5
    outs:
    - models/model.pt
    metrics:
    - models/metrics.json
