stages:
  select_and_export:
    cmd: python src/data/export_data.py
    deps:
    - data
    - src/data
    outs:
    - prepared_data
  train:
    cmd: docker-compose up
    deps:
    - prepared_data
    - models/params
    - src/model
    outs:
    - models/weights
    - models/samples
    - models/metrics
