stages:

  prepare_opix:
    cmd: python src/data/prepare_opix.py
    deps:
    - opix_dataset/
    - src/data/prepare_opix.py
    outs:
    - prepared_opix

  pretrain:
    cmd: sh src/model/pretrain.sh
    deps:
    - prepared_opix
    - src/model
    outs:
    - models/pretrained
    params:
    - models/params/pretrain_hyp.yaml:
      - anchor_t
      - box
      - cls
      - cls_pw
      - copy_paste
      - degrees
      - fl_gamma
      - fliplr
      - flipud
      - hsv_h
      - hsv_s
      - hsv_v
      - iou_t
      - lr0
      - lrf
      - mixup
      - momentum
      - mosaic
      - obj
      - obj_pw
      - perspective
      - scale
      - shear
      - translate
      - warmup_bias_lr
      - warmup_epochs
      - warmup_momentum
      - weight_decay

  prepare_data:
    cmd: python src/data/export_data.py
    deps:
    - data
    - src/data/common
    - src/data/export_data.py
    outs:
    - prepared_data

  fine_tune:
    cmd: sh src/model/train.sh
    deps:
    - prepared_data
    - src/model
    - models/pretrained/weights/best.pt
    outs:
    - models/results
    params:
    - models/params/hyp.yaml:
      - anchor_t
      - box
      - cls
      - cls_pw
      - copy_paste
      - degrees
      - fl_gamma
      - fliplr
      - flipud
      - hsv_h
      - hsv_s
      - hsv_v
      - iou_t
      - lr0
      - lrf
      - mixup
      - momentum
      - mosaic
      - obj
      - obj_pw
      - perspective
      - scale
      - shear
      - translate
      - warmup_bias_lr
      - warmup_epochs
      - warmup_momentum
      - weight_decay

  evaluate:
    cmd: sh src/model/evaluate.sh
    deps:
    - models/results/weights/best.pt
    - src/model
    - prepared_data/test
    metrics:
    - models/metrics/results.json
